services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    networks:
      frontend:
        aliases:
          - topcv.local
          - account.ios.local
      backend:
        aliases:
          - topcv.local
          - account.ios.local
          - employee.ios.local
          - connect.ios.local
          - customer.ios.local
          - order.local
          - dktt.topcv.local
          - job.topcv.local
    depends_on:
      - php-fpm-old

  elasticsearch:
    extends:
      service: elasticsearch
      file: docker-compose.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro

  kibana:
    extends:
      service: kibana
      file: docker-compose.yml
    environment:
      # - ELASTICSEARCH_HOSTS=["http://10.6.34.6:9200"]
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      #         - ELASTICSEARCH_HOSTS=["http://10.14.34.69:9200"]
      #         - ELASTICSEARCH_HOSTS=["http://192.168.2.22:9201"]
      #         - ELASTICSEARCH_USERNAME=elastic
      #         - ELASTICSEARCH_PASSWORD=TO4KH0U1330oKMQ8xfLUX166

  kpi-service:
    build:
      context: ../codes/topcv/main/kpi
      dockerfile: Dockerfile-dev
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
    volumes:
      - ../codes/topcv/main/kpi:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    ports:
      - 8123:8000
    entrypoint: "php artisan octane:frankenphp --watch"
    networks:
      - backend
      - frontend

  php-fpm-old:
    extends:
      file: docker-compose.yml
      service: php-fpm
    build:
      context: ./php-fpm
      args:
        - LARADOCK_PHP_VERSION=${PHP_OLD_VERSION}

  bitwarden:
    image: vaultwarden/server:${BITWARDEN_VERSION}-alpine
    restart: always
    volumes:
      - ${BITWARDEN_LOG_PATH}:/log
      - ${DATA_PATH_HOST}/bitwarden:/data
    environment:
      - DOMAIN=${BITWARDEN_DOMAIN}
      - SMTP_HOST=${BITWARDEN_SMTP_HOST}
      - SMTP_PORT=${BITWARDEN_SMTP_PORT}
      - SMTP_FROM=${BITWARDEN_SMTP_FROM}
      - SMTP_FROM_NAME=${BITWARDEN_SMTP_FROM_NAME}
      - SMTP_USERNAME=${BITWARDEN_SMTP_USERNAME}
      - SMTP_PASSWORD=${BITWARDEN_SMTP_PASSWORD}
      - SMTP_SECURITY=${BITWARDEN_SMTP_SECURITY}
      - SIGNUPS_ALLOWED=${BITWARDEN_SIGNUPS_ALLOWED}
      - INVITATIONS_ALLOWED=${BITWARDEN_INVITATIONS_ALLOWED}
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=${BITWARDEN_WEBSOCKET_ENABLED}
      - DATABASE_URL=${BITWARDEN_DATABASE_URL}
      - LOG_FILE=/log/bitwarden.log
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  keycloak:
    extends:
      service: keycloak
      file: docker-compose.yml
    environment:
      - KEYCLOAK_PRODUCTION=${KEYCLOAK_PRODUCTION}
      - KEYCLOAK_PROXY_HEADERS=${KEYCLOAK_PROXY_HEADERS-''}
